### ISSUE TITLE
Python Blinky docs wrong

### ISSUE THREAD

**Issue by ricl** [ms-iot/samples#129]
Some (all?) of the Python example projects do not have a reference to _wingpio.pyd built in although the docs say that they do.

Either a ref needs adding to the projects or the docs need changing.

**Comment by alanch-ms** [comment]
Sorry for the late reply.  I just double checked the samples.  The reference to _wingpio.pyd is there.  There's a bug in VS where the reference doesn't show up on the solution explorer.  However, if you look at the XML of *.pyproj, you can see the reference there.

**Comment by IoTGirl** [comment]
Confirmed with Alan. No response in more than 1 month - Closing
