### ISSUE TITLE
SerialPort USB Object reference not set

### ISSUE THREAD

**Issue by santmu30** [ms-iot/samples#135]
I am trying to find a solution to the Known Issue Object Reference not Set to an instance of an object when the usb is connected for the first time, I know that if I disconect the usb and reconnect, the problem is gone, but my enviroment is that the USB will be always connected and I need an unattended enviroment, so Please could you help me find a solution for it? i was trying to disable the USB port and enable again but i didnt find any function to it.

Thank You and Kind Regards

Santiago Muñoz

**Comment by serusako** [comment]
Hi,
please try the following workaround - reboot your RPi2 platform and terminate the following process ZWaveHeadlessAdapterApp (shown in App Manager as running app)  before you plug in your USB serial adapter. You can also uninstall this app ZWaveHeadlessAdapterApp to make your changes persist across reboots.

**Comment by zhuridartem** [comment]
ZWave App is no longer enabled by default. Closing issue.
