### ISSUE TITLE
open source DefaultApp

### ISSUE THREAD

**Issue by grahamehorner** [ms-iot/samples#138]
open source the DefaultApp so developers can extend/customise the experience including extending the web pages for remote management.

**Comment by piwi1263** [comment]
Do you mean this https://github.com/ms-iot/samples/tree/develop/IoTCoreDefaultApp ?

**Comment by grahamehorner** [comment]
doh! I feel really stupid now! yes that is the DefaultApp   Thanx for pointing me in the right direction.

**Comment by grahamehorner** [comment]
I'm looking for the source code for the web management page; but can't seem to locate this? @piwi123 any pointers greatly appreciated.

**Comment by ooeygui** [comment]
Thank you for the request. The Web interface cannot be open sourced at this time.
