### ISSUE TITLE
Source for the AllJoyn samples?

### ISSUE THREAD

**Issue by Injac** [ms-iot/samples#15]
I wonder why there are no project and source-files available for the AllJoyn samples. Will you add this code?

**Comment by ooeygui** [comment]
The source files are available in the AllSeen git -  https://git.allseenalliance.org/cgit/dsb.git. We will update the samples to make it more clear.

Hope that helps,
Lou

**Comment by Injac** [comment]
Perfect :) Thanks Lou!
