### ISSUE TITLE
DHT22/AM2302 Not Working with GPIOOneWire

### ISSUE THREAD

**Issue by HeyJude1997** [ms-iot/samples#171]
Currently I am using the DHT22/AM2302 which has a built in 5.1k resistor, using the program provided from https://ms-iot.github.io/content/en-US/win10/samples/GpioOneWire.htm and connected the sensors VCC to 3.3V(Pin1), GND to GND(Pin6), and DOUT to GPIO4(Pin7). Everything seems to be hooked up right but when running the program, no sensor is detected.  I've troubleshooted the sensor on a Linux platform and had no issues, others have reported that the DHT11 works fine with the program.  

I've been stuck on this issue for almost a month now with several threads on different forums open with no luck. If a clear answer is provided that would be much appreciated.

**Comment by jordanrh1** [comment]
What build number are you running (type 'ver' at the SSH prompt)? The DHT11 sample only works on build 10556 and higher.

The sample is right on the edge performance-wise of being able to service the DHT11. If there is significant background activity (e.g. network, USB, disk, video activity) it could prevent the sample from working correctly.

**Comment by HeyJude1997** [comment]
Currently running [Version 10.0.10240](I am still very new to iot so I assume this is an out dated version 10240? downloading version%2810586.0.151029-1700%29 OS image). Here is the model number of the DHT22 as well as the kind I have bought. Model # (SN:150605AB6),  http://www.amazon.com/Temperature-Humidity-Measurement-Appliance-XYG-Study/dp/B0130I6MIC/ref=sr_1_8?ie=UTF8&qid=1449176521&sr=8-8&keywords=dht22

**Comment by HeyJude1997** [comment]
That fixed it.

**Comment by ooeygui** [comment]
Based on the last comment, this sounds like it works now.
