### ISSUE TITLE
AllJoynExplorer crashes on Windows 10 Mobile

### ISSUE THREAD

**Issue by dotMorten** [ms-iot/samples#178]
When deploying the alljoyn explorer to Windows 10 mobile, the app will launch but then crash a second later.

**Comment by dotMorten** [comment]
FYI @zhuridartem

**Comment by zhuridartem** [comment]
Noted. We will attempt to repro and get back to this post.

**Comment by zhuridartem** [comment]
Won't Fix. AllJoyn Explorer is currently not supported on Windows 10 mobile, with no ETA.
Note that DeviceProvider based projects should not be crashing on Mobile, IoT Core, or other editions.

**Comment by dotMorten** [comment]
Sad Panda :-(
Quite useful to have a device next to you to monitor alljoyn services while debugging
