### ISSUE TITLE
When to call AllJoyn AdapterLib::ZWaveAdapter::StartDeviceDiscovery()?

### ISSUE THREAD

**Issue by charlehsin** [ms-iot/samples#18]
If my understanding is correct, AdapterLib::ZWaveAdapter::StartDeviceDiscovery() is only called in the following 2 situations:
1) When the hosting app/service is starting up.
2) When the ZWave SDK notifies Type_DriverRemoved/Failed.

What this means is that current DSB implementation (or at least this sample code) does not support "plug-and-play" type device addition. If a new ZWave device is added, after ZWaveAdapter hosting app/service is already running, then this new device won't be detected.

Is my understanding correct?
If my understanding is correct, is there any plan to modify current DSB implementation to support such "plug-and-play" scenario?

Thanks,
Chih-fan

**Comment by zhuridartem** [comment]
Hello Chih-fan,

There are two plug and play stories here:
1.	Plug in Z-stick dongle. 
2.	Pair new Z-Wave device with already running dongle

The first story is supported. When StartDeviceDiscovery( ) is called, it asks the OpenZwave stack to open the serial port. OpenZWave will keep on retrying for ‘DriverMaxAttempts’ (specified in Options.xml, default = 0), until it is able to open the port. If DriverMaxAttempts are attempted without successful opening of the port, DriverFailed is notified, in which case the ZWaveAdapter will restart the discovery after 30 seconds. DriverMaxAttempts is by default 0, which means infinite attempts. Hence, the ZWave stack will keep on retrying until successful. You should be able to remove and reinsert the Z-Stick with ZWave DSB running, and devices should disappear/reappear on the bus.

For the second story, I don't think you are allowed to pair a new device while the Z-stick is already plugged in and running. But, you should be able to remove the stick, pair it and then re-insert into the USB port and new device should show up. ZWave DSB can be left running and it will pick up device removals (when dongle is removed) and device arrivals (after re-insert). We did not try it out though. 

Please let us know on your findings.
