### ISSUE TITLE
Current Blinky web page on IoT contains proof reading error

### ISSUE THREAD

**Issue by ricl** [ms-iot/samples#181]
https://ms-iot.github.io/content/en-US/win10/samples/Blinky.htm

Still references 'None' in the text box in item 3 although the picture alongside it is correctly showing the new choices under u1 of Universal (Unencrypted Protocol).

**Comment by bfjelds** [comment]
Thanks for the feedback!  We will correct this ASAP.

**Comment by bfjelds** [comment]
Pull Request to fix this: https://github.com/ms-iot/content/pull/747

**Comment by ricl** [comment]
That should do it
