### ISSUE TITLE
Pinmappings do not reflect Serial Tx/Rx available from 10586 on

### ISSUE THREAD

**Issue by ricl** [ms-iot/samples#182]
https://ms-iot.github.io/content/en-US/win10/samples/PinMappingsRPi2.htm

Pins 8 & 10 are still marked 'Reserved'.

**Comment by dankuo** [comment]
Thanks! Pin mappings have been updated to reflect the addition of Serial UART.

https://ms-iot.github.io/content/en-US/win10/samples/PinMappingsRPi2.htm
