### ISSUE TITLE
C# and VB Background Task project missing reference to .NET Core

### ISSUE THREAD

**Issue by dotMorten** [ms-iot/samples#199]
When you download the IoT Core Project templates and create a new background task, the project won't compile. You need to open up project.json and add a reference to .NET Core.

![image](https://cloud.githubusercontent.com/assets/1378165/12301305/18cd3ee8-b9d4-11e5-8ebb-222345555778.png)

```
The dependencies entry is missing NETCore 5. When you add this, the project will compile again.
"dependencies": {  
  +      "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0"  
},  
```

Steps to reproduce:
- Download and install the IoT Core Project Templates from the VS Gallery
- Create a new C# `Background Application (IoT)` project.
- Compile and observe the 41 build errors.
- Open up project.json and observe that the `dependencies` section is empty
- Add `"Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0"` to the dependencies and build (everything is now good)

**Comment by bfjelds** [comment]
The dependency should be added (as it is for the other C#/VB UWP projects) when the template is instantiated.  

Can you look at the versions you have installed in About Visual Studio?

**Comment by bfjelds** [comment]
Please reopen this if you continue seeing this issue!
