### ISSUE TITLE
Unable to launch Background Application from Device Portal

### ISSUE THREAD

**Issue by koapeadu** [ms-iot/samples#205]
When Background Applications (and headless Alljoyn Apps),  I am unable to launch them from the Device Portal.

There's just a javascript alert which says 
    "Failed to start package 
    AppNameHeadless_ef679m
    AppNameHeadless"

**Comment by bfjelds** [comment]
This is an unfortunate limitation of the Device Portal currently.  It can only start headed applications.  

As a workaround, in the Processes page, you can use Run command to execute this command to start a background application (by specifying it as one of the startup apps):

```
iotstartup add headless AppNameHeadless
```

This will start the background application.  **NOTE: this will configure IoT Core to ensure that this background application is always running (so if it crashes or exits, the OS will restart it ... also, if you restart the device, the background application will be started)**

To undo this, you can execute this command in the Processes page:

```
iotstartup remove headelss AppNameHeadless
```

We are working on adding a simpler way to start background applications.
