### ISSUE TITLE
Wiki and Samples web site hard to read!

### ISSUE THREAD

**Issue by mgaman** [ms-iot/samples#207]
Hi,
The current color scheme of pale gray text against a white background is a nightmare to read.
Just look at a basic Wiki page, https://en.wikipedia.org/wiki/Main_Page, much much easier on the eyes.

Am I the only one that finds this a problem?

**Comment by bfjelds** [comment]
Sorry for the inconvenience!  

For the Samples, I believe we are simply using the standard Git UI color scheme ... I'm not aware of how much customization is available, but we will look into it.

**Comment by IoTGirl** [comment]
Feedback taken by Dev Team member - Closing issue
