### ISSUE TITLE
IOTCoreDefault app OOBEWelcome screen doesn't present well on Phone screen

### ISSUE THREAD

**Issue by mahoekst** [ms-iot/samples#215]
Screen doesn't adapt to smaller (horizontal) sizes, you can't get through the language selection screens etc.

**Comment by bfjelds** [comment]
Thanks for the feedback!  We will look into this as soon as we can!  

What screen size did you experience this on?

**Comment by MahmoudGSaleh** [comment]
Thanks for bringing up this issue. 
We've updated the OOBE screen XAML, so it's got a responsive UI now and should adapt to any screen size (240px or more).

**Comment by mahoekst** [comment]
great, I can get through the pages now on a mobile device.
