### ISSUE TITLE
Drivers on Raspberry Pi (PWM & DirectX)

### ISSUE THREAD

**Issue by deivid77** [ms-iot/samples#220]
Hi,

Are you going to support PWM in the framework like Python does?.
I would like to get a piezo buzzer working directly without C++ Bus Provider Library or Lightning drivers (the sound is not enough loud)

I would also like to know an estimated release date for Direct-X support

Thanks in advance.
David Blanco

**Comment by mjmeans** [comment]
There is a PWM driver with settable I2C address in project https://github.com/jbienzms/iot-devices.

**Comment by IoTGirl** [comment]
Raspberry Pi does not support Direct X - https://social.msdn.microsoft.com/Forums/en-US/457f1b43-2779-4a92-abcd-3257be41e599/directx-support?forum=WindowsIoT
