### ISSUE TITLE
IoTCoreDefaultApp - DeviceType

### ISSUE THREAD

**Issue by grahamehorner** [ms-iot/samples#233]
at present the IoTCoreDefaultApp has hardcoded DeviceType enum for the hardware supported platforms, consider externalising this these values so as/when new hardware platforms become available a simple config file update is needed to:-
1. detected what hardware platform the application is running on
2. locate and load the appropriate hardware platform logo/display name
3. load the correct values for the GPIO pins using in tutorials etc.

**Comment by bfjelds** [comment]
Thanks for the comment.  This is a great suggestion and we will add it to our backlog of items!

**Comment by grahamehorner** [comment]
This could be as simple as providing a resx for the board named something like RaspberryPi.resx, RaspberryPi3.resx, MinoboardMax.resx etc. which can be dynamically loaded.

**Comment by IoTGirl** [comment]
Feedback taken by IoT Team member - closed
