### ISSUE TITLE
IoTDefaultApp - IoT Protocol Gateway

### ISSUE THREAD

**Issue by grahamehorner** [ms-iot/samples#240]
add the ability to action as an azure-iot-protocol-gateway to the IoTDefaultApp; this would allow the Windows 10 IoT Core to become a cheap gateway for devices that use/support MQTT/AMQP as not every device has/will support AllJoyn or has a AllJoyn bridge.

*this functionality could be toggled no/off according to deployment requirements and/or dynamically loaded/injected using DependancyInjection

**Comment by IoTGirl** [comment]
Hi GrahamHorner,  This issue has been reviewed and your feature request has been passed to the Azure Team that supports gateway solutions.  We have no way of tracking it from this end so this request will be closed.  Sincere thanks for your request/idea.  IoTGirl
