### ISSUE TITLE
BlinkyWebServer is failing  because the appService connection is empty

### ISSUE THREAD

**Issue by bfjelds** [ms-iot/samples#25]
Original issue found by BasVeenendaal in pull request (https://github.com/ms-iot/samples/pull/24):

"There is one line of code:
This part should contain the information for appService.AppServiceConnection: var appService = taskInstance.TriggerDetails as AppServiceTriggerDetails;
The appService.AppServiceConnection is only empty buth the appService contains the values needed. So that’s how I came to my “fix” (maybe more a workaround)."

Workaround (lines highlighted with '-->'):

    public void Run(IBackgroundTaskInstance taskInstance) 
    {
    ...
              var appService = taskInstance.TriggerDetails as AppServiceTriggerDetails;
    -->      appService.AppServiceConnection.PackageFamilyName = appService.CallerPackageFamilyName;  
    -->      appService.AppServiceConnection.AppServiceName = appService.Name;  
    ...
    }

**Comment by PatGet** [comment]
Renaming the private AppServiceConnection var of the HttpServer class fixes this scope issue and the resulting null issue.
