### ISSUE TITLE
AllJoyn DSB Adapter configuration and security

### ISSUE THREAD

**Issue by charlehsin** [ms-iot/samples#26]
In my understanding, AdapterConfig::SetConfig() will overwrite "options.xml", that is used by OpenZWave SDK.  I have the following 2 questions:
1. After SetConfig(), the current implementation only updates “options.xml”. Shouldn’t the codes reset or restart the AllJoyn network to use the new configuration? I didn't see this part implemented in the codes.
2. This options.xml file has a “NetworkKey” field that can be used for secure devices. See https://github.com/OpenZWave/open-zwave/wiki/Adding-Security-Devices-to-OZW .  Not sure if current DSB implementation + ZWaveAdapterUAP demo codes support this or not for secure devices?
Thanks,
Chih-fan Hsin

**Comment by zhuridartem** [comment]
Hello Chih-fan Hsin,

1)	The team made a design decision that we could not know in advance if an adapter change would require a restart or not.  We decided it was up to the adapter writer and they could modify the bridge if desired….or simply require a system reboot. The bridge config update should initiate a bridge restart. 

2)	We do not support Secure inclusion of devices. It has to be done through external applications like Zwave Control Panel. We did have to add the NetworkKey value to Options.xml in the past for some network that had a paired secure device, but cannot say whether the secure device was truly usable at that point and if additional effort is required to enable such devices.

Hope this helps!
Artem.
