### ISSUE TITLE
GpioOneWire UWP C# QueryPerformanceFrequency

### ISSUE THREAD

**Issue by ScottLiuGitHub** [ms-iot/samples#267]
I am trying to convert GpioOneWire to C#. How should I 
QueryPerformanceFrequency in UWP? Thanks!

**Comment by jordanrh1** [comment]
Use `System.Diagnostics.StopWatch`.

**Comment by IoTGirl** [comment]
Hi Scott,
I am closing based on answer given.  Please reopen if this does not address your question.
Sincerely,
IoTGirl
