### ISSUE TITLE
Cannot deploy app to Raspberry Pi 2 (win10 IOT Core)

### ISSUE THREAD

**Issue by muziekklas** [ms-iot/samples#28]
In Visual Studio 2015 RC (Windows 10 Preview) an error occures while deploying:
Error : DEP0800 : The required framework "C:\Program Files\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.NET.CoreRuntime\1.0\.\AppX\ARM\Microsoft.NET.CoreRuntime.1.0.appx" failed to install.

**Comment by bfjelds** [comment]
I'm sorry that the samples aren't working for you!  To help us track down the problem and fix it, can you please specify which sample you are seeing this error for?

**Comment by muziekklas** [comment]
Blinky (normal one)
I also followed steps on http://ms-iot.github.io/content/en-US/win10/samples/Blinky.htm but mainly used the code from the repo

**Comment by muziekklas** [comment]
I fixed it by reflashing the SD card. I assume it was not correctly flashed the first time because I see more Processes on the webUI
