### ISSUE TITLE
Consider I2C Version of SSD1306 OLED 128x64 Display

### ISSUE THREAD

**Issue by EdiWang** [ms-iot/samples#285]
I see we have a "SPIDisplay" sample in the project. However, there's also I2C interface version for this display. Could you provide an I2C version of the SSD1306 OLED display sample?

Thanks in advance!

Reference: https://github.com/adafruit/Adafruit_SSD1306/tree/master/examples/ssd1306_128x64_i2c

**Comment by IoTGirl** [comment]
Hi Edi,
StepnanGordan has already stated that he will provide a sample in the previous item you answered. See https://github.com/ms-iot/samples/issues/284.  I am closing this as a duplicate.
Sincerely,
IoTGirl
