### ISSUE TITLE
AllJoyn DSB configuration and CSP and MDM provider

### ISSUE THREAD

**Issue by charlehsin** [ms-iot/samples#29]
Hi, based on the Microsoft's "AllJoyn -DSB whitepaper v1.0.pdf", it seems that System Center or InTune can use "MDM WMI bridge provider" -> AllJoyn Management "Configuration Service Provider" -> AllJoyn bus "com.microsoft.alljoynmanagement.config" to control the AllJoyn - DSB configuration.

Is this feature already implemented in the current release DSB sample codes?

I cannot find the corresponding "AllJoyn" CSP or MDM provider in the following 3 links: 
https://msdn.microsoft.com/en-us/library/windows/hardware/dn920025%28v=vs.85%29.aspx
https://msdn.microsoft.com/en-us/library/dn905224(v=vs.85).aspx 
https://msdn.microsoft.com/en-us/library/windows/hardware/dn904985(v=vs.85).aspx .

Can anyone point me to the CSP and MDM WMI provider information about AllJoyn Management?

Thanks,
Chih-fan Hsin

**Comment by mwgladding** [comment]
Hi Chih-fan. The CSP will be available as part of the IoT Core operating system, and not in the DSB code. We should have documentation available for the CSP in the next few weeks. Please note that we will be working with both first and third party MDM providers to build MDM management solutions for IoT Core. The timeline for MDM support for IoT Core has not been finalized at this point in time.
