### ISSUE TITLE
VB version Blinky ?

### ISSUE THREAD

**Issue by fumiya-kume** [ms-iot/samples#292]
Is there a VB version of the Blinky?

**Comment by IoTGirl** [comment]
Hi fumiya-kume,
There is no VB version but there is a C# version - See https://developer.microsoft.com/en-us/windows/iot/win10/samples/blinkyheadless.  There is no reason you could not use the logic in the C# version to create a VB project.

More sample links are available from https://developer.microsoft.com/en-us/windows/iot/win10/StartCoding.htm

Sincerely,
IoTGirl
