### ISSUE TITLE
IoTBrowser

### ISSUE THREAD

**Issue by rudman11** [ms-iot/samples#306]
Is there a way to set the proxy settings for the IoTBrowser running on RasPi 3 using Windows IoT Core?

**Comment by IoTGirl** [comment]
I'll need to do more digging but I suspect you will need to use a UWP version of WinHTTP.SetProxy.  Here is a previous version of the documentation [https://msdn.microsoft.com/en-us/library/windows/desktop/aa384069(v=vs.85).aspx](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384069%28v=vs.85%29.aspx) 

Update: Did more digging and did not come up with an easy solution so I have asked the IoT Team to review this scenario (8305489).

**Comment by IoTGirl** [comment]
Hi Rudman,
The team has accepted this request as a work item and have added it to their backlog. 

> We are working on support for configuring the proxy on IoT via netsh.exe command. (9113049)  

As this team works on the agile model, I can't give you a timeline for this feature to be implemented.

Sincerely,
IoTGirl

**Comment by IoTGirl** [comment]
NOTE: **Add WinHTTP netsh helper for proxy configuration in IoTCore** images was checked in to address this request and should appear in an upcoming Insider build.
