### ISSUE TITLE
DigitalSignageUAP

### ISSUE THREAD

**Issue by ghost** [ms-iot/samples#311]
specify a new config file to read from at the location you specify - this feature does not work. I have tried many times in different ways including string "Assets\confignew.xml" with or without quotes but it never work. The result is it will always pick up the original @"Assets\config.xml". Can someone please look at this. Thanks!

**Comment by zhuridartem** [comment]
Thank you for reporting. My apologies for taking so long - 
Should be fixed with https://github.com/ms-iot/samples/pull/450

**Comment by zhuridartem** [comment]
This issue is now fixed.
