### ISSUE TITLE
Vb Samples

### ISSUE THREAD

**Issue by tig4647** [ms-iot/samples#33]
I am having a terrible time attempting to convert the headless example (blinky) to vb.net . Is there any way to provide one example for vb that we can push from? For me, i have no plans to utilize the WPF portion and want to be able to use headless but just cannot seem to set it up correctly.

**Comment by jessekaplan** [comment]
If you build a "Universal Windows" Blank App (XAML) you can easily build a UI app for IoT Core. We'll have a few headless VB samples available by RTM as well.

**Comment by tig4647** [comment]
Thanks for adding, also the template helps for VS 2015
