### ISSUE TITLE
DHT22 sensor 

### ISSUE THREAD

**Issue by saicharan747** [ms-iot/samples#336]
I just did your application on windows 10 iot  core and I  tried with both the  sensors like dht11 and dht22 and the  application is deploying on to my pi correctly and the output is same as yours and problem is like I cannot able to see the readings on it (the connections are given exactly like what you have said and brought almost 2-3 sensors for checking but I still get the same issue).so can u say me what could be the problem!

**Comment by IoTGirl** [comment]
Hi Saicharan,  Please take a look at [http://stackoverflow.com/questions/30082322/windows-10-iot-raspberry-pi-2-dht22-am2302](http://stackoverflow.com/questions/30082322/windows-10-iot-raspberry-pi-2-dht22-am2302) as it explains the precision required for the sensor you are asking about.
Sincerely, IoTGirl
