### ISSUE TITLE
Blockly not working

### ISSUE THREAD

**Issue by jwillmer** [ms-iot/samples#342]
## Setup
- I have a Raspberry 3 with sense hat
- I deployed the latest Windows IOT on it. 
- I used the IOT Dashboard to deploy blocky.
## Problems
- ~~With the stable Windows IOT image I can't reach the web interface of blockly - config interface is available~~
- With the preview image I can reach the web interface of blockly but the `run` command does not produce any change on the sense hat.

**Comment by jwillmer** [comment]
After a restart the heartbeat example is working on Windows IOT Preview but updating the heartbeat does not work. 

I get this exception on the command line of Chrome:

```
192.168.1.130/:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
```

**Comment by gourabSh07** [comment]
I also have almost same problem Windows IOT image I can't reach the web interface of blockly 
I am using windows build  14393

**Comment by jwillmer** [comment]
I was now able to reach the web interface on the stable build after redeploying the build and the app. 

I also managed to get the heartbeat to run after pressing countless times on run but the method is not relayent.

**Comment by IoTGirl** [comment]
Can you please provide a link to the Microsoft Sample you are referring to that is failing?

**Comment by jwillmer** [comment]
[IOT Blockly](https://github.com/ms-iot/samples/tree/develop/IoTBlockly)

FYI the blockly example is one of 4 examples that you can automatically download and install to your Raspberry PI via the `IOT Dashboard`. I think it is pretty bad that a promoted example does not work.

**Comment by IoTGirl** [comment]
Excellent! Thank you for the link. Assigned @rachitb777 to take a look.

**Comment by rachitb777** [comment]
@jwillmer Do you see IoTBlocklyBackgroundApp [Startup] listed in the apps page in Windows Device Portal?

**Comment by jwillmer** [comment]
Of course, how else would I be able to browse to the website?

**Comment by alecont** [comment]
thanks for the feedback! We'll look into this in the next couple of days. We made a couple of changes to the source code here on github which are not reflected yet on the appx deployed by IoT Dashboard.

**Comment by OwenBrotherwood** [comment]
@jwillmer 
How about testing with and without Windows IoT Remote Server enabled.
Both the example and the remote server seem to be using the same port, 8000.
That is, do not start the remote server and deploy the sample.

Edit
Hw: 10.0.14393.0 Pi3
Commit: https://github.com/ms-iot/samples/commit/44daa3131eeb71d8b60215115b12f99f403a93d0

**Comment by jwillmer** [comment]
@OwenBrotherwood I can try it but the `Windows IoT Remote Server` is not using port `8000` it uses `8080` as default. Anyhow I think the example should work without any hack.

**Comment by OwenBrotherwood** [comment]
@jwillmer : 
Windows IoT Remote Server is NOT started by default: it is up to the administror to start it: a choice that can be affected by the other software chosen to be run on the unit ie NOT a hack
The Web Interface uses 8080 (where one enables Remote Server) 

@alecont The example will work, however the port used should be changed from 8000 to some other port plus a clear indication where in the source code the chosen default can be changed or made as a configurable option.
I have not found out yet where the port 8000 is set: given some information, I can create a pull request.

**Comment by jwillmer** [comment]
@OwenBrotherwood I mixed up the `Device Portal` with the `Windows IoT Remote Server`. The `Windows IoT Remote Server` was not active. I deployed a clean install of `Windows IoT` and used the `IoT Dashboard` to deploy `blockly`

**Comment by OwenBrotherwood** [comment]
@jwillmer 
Is your status, No Windows IoT Remote Server aktive and Blockly works?

**Comment by jwillmer** [comment]
Yes, I see the Blockly web page but I am unable to start any template.

**Comment by OwenBrotherwood** [comment]
@jwillmer OK I do not have a sense hat: I want to use the example as a start to integration to https://www.microbit.co.uk/ which has strong links to microsoft
-- and create a pull request for the result if I ever get that far.
Edit: https://github.com/ms-iot/samples/blob/6d70b2a8f1d951a59491c180ee87a019c869b1f8/IoTBlockly/IoTBlocklyHelper/SenseHat.cs#L235
Edit Edit: https://github.com/ms-iot/virtual-shields-universal Arduino but make it micro:bit

"start any template" : do you mean get the template (program) to run and show a result on the sense hat?

**Comment by jwillmer** [comment]
@OwenBrotherwood Yes, there is for instance a heartbeat demo that I tryed to run

**Comment by OwenBrotherwood** [comment]
@jwillmer /cc @IoTGirl @alecont @rachitb777 
The line of code that dictates port 8000  (grep -r 8000 *)
I have to double check the port used by Remote server and try and make a pull request with the port as a configurable option with a default that does not conflict with the standard ports used with the startable services, such as Remote Server 
https://github.com/ms-iot/samples/blob/44daa3131eeb71d8b60215115b12f99f403a93d0/IoTBlockly/IoTBlocklyBackgroundApp/StartupTask.cs#L69

I also took the time to do:

```
root@home:/mnt/c/Users/owen/Documents/GitHub/samples# grep -r 'server\.Listen(8000)' *
IoTBlockly/IoTBlocklyBackgroundApp/StartupTask.cs:            server.Listen(8000);
root@home:/mnt/c/Users/owen/Documents/GitHub/samples#

```

(from Microsoft's Windows 10 Canonical/Ubuntu Bash prompt)

@jwillmer 
I will receive a sense in a few days, then I will try to use the sample as intended

**Comment by OwenBrotherwood** [comment]
quick update and I may forget to update when finished
A change of port to 8001 did not help.
I have not as yet scanned if the port is already used
I disabled the remote server again as I want to see the Astro work.
I have a blicking red heart

"And it is goodnight from me at the Windows 10 IoT workshop"

Edit:
[Coding Pirates Silkeborg Lyd og Lys](https://www.facebook.com/CodingPiratesSilkeborgLydOgLys/posts/1128308170550314)

**Comment by jwillmer** [comment]
@OwenBrotherwood so now you can reproduce the problem?

**Comment by OwenBrotherwood** [comment]
@jwillmer The example works if remote server is disabled. 

The device was used for 8 hours at this Maker Faire in Århus, Denmark with the Blocky example 

The last minute of the video shows the stand I was playing at (with 7 inch red screens)

https://www.facebook.com/karinhoegh/posts/10154792942724610

**Comment by gourabSh07** [comment]
After disabling  Remote Server i was able to get web interface of iot blockly but heart example is not working for me do i have to do something else to run it ??

**Comment by OwenBrotherwood** [comment]
The heart example works for me

**Comment by jwillmer** [comment]
Works now (for me) with the latest IOT Preview build: `10.0.14931.1000`

Steps to reproduce:
- Start Win10 IOT Core Dashboard
- Insert empty SD card
- Deploy latest IOT Preview build
- Setup WIFI
- Use Win10 IOT Core Dashboard to install blockly
- Browse to x.x.x.x:8000

**Comment by dnkmk** [comment]
Shouldn't that be version 14971.1000?

Sent from my Windows 10 phone

**Comment by jwillmer** [comment]
I installed the latest preview build version the Win10 IOT Dashboard found. For me it was 14931 but I see right now that there is a update scheduled.

**Comment by dnkmk** [comment]
Okay,

Could it be you forgot to choose “Custom” for device type during new device setup?
Not choosing custom results in a production setup I think….

Van: Jens Willmer [mailto:notifications@github.com]
Verzonden: donderdag 1 december 2016 15:29
Aan: ms-iot/samples <samples@noreply.github.com>
CC: dnkmk <daniel.komkommer@outlook.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [ms-iot/samples] Blockly not working (#342)


I installed the latest preview build version the Win10 IOT Dashboard found. For me it was 14931 and the admin web panel tells me there are no updates available for the system.
