### ISSUE TITLE
DigitalSignageUAP Video

### ISSUE THREAD

**Issue by PRIMETSS** [ms-iot/samples#345]
**Device Name:  Win10CoreIoT
Device Model:   Raspberry Pi 3
OS Version: 10.0.14393.0**

and

**Device Name:  Win10CoreIoT
Device Model:   Raspberry Pi 3
OS Version: 10.0.14393.187**

Debug rate counter  
[App fps] [App cpu] 
000           002

[Sys fps] [Sys cpu]
064         003

The sample app on a Pi3 is displaying poor video, missing frames. MP4 or WMV
using Pi 7" Touch Display, or via HDMI
(No Audio either via HDMI)
Debug fps rate counter doesn't appear to be accurate.
Is this what other people are seeing?
Any more news or a plan to get better video performance? GPU Support maybe?

Exact video works fine as .wmv or .mp4 on Raspbian

**Comment by IoTGirl** [comment]
Hi PRIMETSS,
Have you tried this on other IoT Core platforms?  There are known issues with the GPU on RPi not supporting Direct X and therefore the graphics performance suffers. 
Sincerely,
IoTGirl

**Comment by PRIMETSS** [comment]
Not yet, does anyone have recommendations on board on a board they have tried that doesn't have this problem?

**Comment by IoTGirl** [comment]
We have a video loop running on an MBM at the office without issue. Basic HD TV resolution, nothing fancy.  I would take a look at some of the other IoT Core offerings at [https://azure.microsoft.com/en-us/documentation/articles/iot-hub-tested-configurations](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-tested-configurations) that are based on the same Intel chipset.

**Comment by IoTGirl** [comment]
No update for more than 1 month - closing.  Please see the MSDN IoT Forums for more questions regarding IoTCore.
