### ISSUE TITLE
Can't deploy OIC Adapter to remote device

### ISSUE THREAD

**Issue by dotMorten** [ms-iot/samples#346]
Something is wrong with the project settings of the Headless Adapter app in the OIC service. I don't get to pick a remote device.

![image](https://cloud.githubusercontent.com/assets/1378165/19315467/a1599edc-9052-11e6-978d-75acede2b418.png)

The project debugging settings show this:
![image](https://cloud.githubusercontent.com/assets/1378165/19315558/ffb836a0-9052-11e6-81a3-fe62bb9cf093.png)

Trying to change it to remote device, it just switches back to this unsupported setting when hitting apply.

I'm using Visual Studio 2015 Update 3

**Comment by dotMorten** [comment]
Seems like something is borked on my Visual Studio installation. Doesn't work for any C++ background tasks (C# projects works however).

**Comment by lflct** [comment]
I just tried opening that project in VS 2015 Update 3 and I can see the Remote Device option in the list of debuggers, so I believe you're right, the problem is not with the project itself. Make sure you have the latest files, though, just in case.
