### ISSUE TITLE
In the invitation to contribute, first link is broken: Aceess Not Authorized

### ISSUE THREAD

**Issue by djaus2** [ms-iot/samples#350]
You must have a page on the **IoT Core samples page** corresponding to your code <-- This link

**Comment by IoTGirl** [comment]
Page is: [https://github.com/ms-iot/samples/blob/develop/README.md](https://github.com/ms-iot/samples/blob/develop/README.md)

Bad Link: [https://developer.microsoft-int.com/en-us/windows/iot/samples](https://developer.microsoft-int.com/en-us/windows/iot/samples)
Correct Link: [https://developer.microsoft.com/en-us/windows/iot/samples](https://developer.microsoft.com/en-us/windows/iot/samples)

**Comment by IoTGirl** [comment]
This should be fixed now.

**Comment by djaus2** [comment]
OK it works now thx.
Closing

**Comment by IoTGirl** [comment]
Thanks!

**Comment by djaus2** [comment]
IoTGirl,
I am just trying to get my head around contributing to the ms-iot/Samples repository.
To get things going, I have created a simple project to add, rather than modify an existing project.

OK I have forked and cloned the whole repo and will add my project as a new folder.
I will create a README.md for my project.

My question is what how do I action: You must have a page on the IoT Core samples pagehttps://developer.microsoft.com/en-us/windows/iot/samples corresponding to your code.

Thx david

**Comment by djaus2** [comment]
So do I need to get an .md file into https://github.com/ms-iot/content/tree/develop/en-US/Samples?
In my case my project is called NoPopUps so I will need https://github.com/ms-iot/content/tree/develop/en-US/Samples/NoPopups.md??
So do I need to for the contents repo, place my NoPopups.md there and get it accepted, its sounding a bit recursive??

**Comment by IoTGirl** [comment]
Hi David,
You need a description for the samples page and a page for your sample, does that clarify? If you take a look at some of the other samples in the repository you should get an idea of what is needed.
Sincerely,
IoTGirl
