### ISSUE TITLE
Adding a new project to Samples ??

### ISSUE THREAD

**Issue by djaus2** [ms-iot/samples#357]
OK so if I wish to improve the code of a Samples project I fork Samples into my GitHub workspace make the improvements then do a Pull Request back.

But what if I wish to add a new project to Samples? I have forked Samples to my GitHub space and added my new project folder to the forked Samples folder. I have created a README.md in the root of the new project folder and also added a detailed **projectname.md** there as well. Now I am ready to do a Pull Request back.  OK But how do I get my **projectname.md** into the correct location?

Thx

**Comment by djaus2** [comment]
I'm working on a "parallel" site to list Community ms-iot samples

**Comment by ooeygui** [comment]
Hi @djaus2 
Our documentation is currently set up to be localized in ms-iot/content. For example, the documentation for HidInjector project which is on the ms-iot/Samples site is actually in content https://github.com/ms-iot/content/blob/develop/en-US/Samples/HidInjector.md.

To add a sample: 

  * Add fork the samples repo and content repo.
  * Add your code to samples, and documentation to content.
  * Submit a PR for Samples
  * Once committed, submit the documentation to content.

We have a script which munges the whole thing for publish, so it will take time to be public.

hope that helps.
Lou
