### ISSUE TITLE
Add save functionallity to blockly example

### ISSUE THREAD

**Issue by jwillmer** [ms-iot/samples#377]
The blockly example is really cool but it would be great to save 1-2 self made examples to show friends and tell `I coded that!`.

**Comment by IoTGirl** [comment]
Hi Jay,
You should be able to make your own projects and even build your own images with the information that can be found through WindowsOnDevice.com.  Specifically please see [WindowsOnDevice.com>Samples](https://developer.microsoft.com/en-us/windows/iot/samples).
Sincerely,
IoTGirl
