### ISSUE TITLE
read access violations when accessing AllJoyn properties with DeviceProviders

### ISSUE THREAD

**Issue by v-tbert** [ms-iot/samples#382]
In various places where AllJoynInterface m_properties is accessed it can lead to a read access violation. For example, in AllJoynInterface::Shutdown sometimes gets an access violation on m_properties->Clear() even though m_properties itself is not null. 

0xC0000005 occurred
Exception thrown: read access violation.
_Pnext was 0xDDDDDDE1.

**Comment by IoTGirl** [comment]
Hi v-tbert,
No specific to only alljoyn but I would expect such a violation if I attempted to access any object property after it was shut down. Can you please provide far more detail as to how this message is generated and why you think it is in error?
Sincerely, IoTGirl

**Comment by IoTGirl** [comment]
Closing - No response
