### ISSUE TITLE
SerialUART not working

### ISSUE THREAD

**Issue by Tamer-Gamal** [ms-iot/samples#390]
Hi,
i'm using the SerialUART in both Pi3 and PC to send/receive string/bytes anything , the data that i sent is not the data i receive, i tried everything, first i got error that there's no Mapping Encoding so i changed the string and send Encoding.UTF8.getBytes and receive Encoding.UTF8.getString but the Bytes that i receive is not the same at all. do i missing anything.

Update : i tried to receive the data by Sniffing on the SerialPort using  Hercules and SerialMonitor and it's the same.

PC: Win10 Ent.
Pi3 with IoT latest.
the cable UART is tested and working fine.

Thank you in advance.

**Comment by IoTGirl** [comment]
Hi Eg-Virus,
There are known issue with the RPi3 miniUart.  Please try other settings or use a device with a full UART implementation.

See https://social.msdn.microsoft.com/Forums/en-US/b1d0a1f3-3ef2-4b74-afa9-f0a75e530a64/accessing-pure-uart-on-windows-10-iot?forum=HardwareBoards 

Sincerely,
IoTGirl
