### ISSUE TITLE
Community Site for ms-iot Samples

### ISSUE THREAD

**Issue by djaus2** [ms-iot/samples#392]
I've published a parallel site to this for IoT Community to publicise their GitHub projects.
[http://www.sportronics.com.au/ms_iot_Community_Samples](http://www.sportronics.com.au/ms_iot_Community_Samples)
You post your project's MD file (eg its ReadMe) and complete some information about the project and subject to approval it get gets listed in a searchable and sortable list.

**Comment by IoTGirl** [comment]
Hi DJaus2,
Many thanks for that alternate sample location.  However, this forum is for issues related to the GitHub content. Closing as there is nothing for MS to address here.
Sincerely,
IoTGirl
