### ISSUE TITLE
Can camera apps run with the RPI camera module?

### ISSUE THREAD

**Issue by piffarettig** [ms-iot/samples#395]
I got the [camera module from the RPI](https://www.raspberrypi.org/products/camera-module/), and I was wondering if any of the samples included here can work properly with it. I didn't find anything about the camera module and Windows IoT Core.

For example the [video capture sample](https://github.com/ms-iot/samples/tree/develop/VideoCaptureSample) or [web cam one](https://github.com/ms-iot/samples/tree/develop/WebcamApp/CS
)

If that's the case, how?

**Comment by brandonzuech** [comment]
The module is currently not supported by windows iot. Your only option atm is USB based cameras

**Comment by piffarettig** [comment]
Thanks!
