### ISSUE TITLE
Can I run this sample on a Raspberry Pi?

### ISSUE THREAD

**Issue by piffarettig** [ms-iot/samples#396]
I am sorry to ask this question here, but I am afraid I haven't received any answer yet in the other forum.

Is a Cognitive Services sample I wanted to run on a RPI running Windows IOT Core.

 [This is my question](https://github.com/Microsoft/Cognitive-Samples-IntelligentKiosk/issues/6)

Whenever I try to deploy the code to the remote device, it asks me for a Windows Phone or to use an Emulator.

I think the Error Code was DEP3310

Thanks in advance!

**Comment by IoTGirl** [comment]
Closing as you have an answer at your prior post.
