### ISSUE TITLE
Is there a guide available for this project?

### ISSUE THREAD

**Issue by florindpreda** [ms-iot/samples#412]
Hello, 

I'm new to the Microsoft IoT Core. I managed to setup and run the Blinky app but now I'm looking on how to connect my Raspberry PI 3 to Azure and PowerBI.

I found the **Azure/WeatherStation.PowerBI** project which I would like to run but I'm not sure what are the dependencies for it. Is there a guide page or file available?

Thanks

**Comment by IoTGirl** [comment]
There is a blog at [https://blogs.msdn.microsoft.com/iot/2016/01/26/using-power-bi-to-visualize-sensor-data-from-windows-10-iot-core/](https://blogs.msdn.microsoft.com/iot/2016/01/26/using-power-bi-to-visualize-sensor-data-from-windows-10-iot-core/)

**Comment by IoTGirl** [comment]
@florindpreda  As you have no further questions I am closing your issue.
