### ISSUE TITLE
NotepadService.StartupTask should handle IBackgroundTaskInstance::Cancel events.

### ISSUE THREAD

**Issue by johngallardo** [ms-iot/samples#420]
If it doesn't, then when the task gets cancelled, the process may be terminated.

**Comment by IoTGirl** [comment]
Hi Paul,
Is this addressed by your other Pull request?
Sincerely,
IoTGirl

**Comment by paulmon** [comment]
Yes. https://github.com/ms-iot/samples/pull/421
