### ISSUE TITLE
Driver Deployment Task Failed: CBS Commit

### ISSUE THREAD

**Issue by CaseyLu** [ms-iot/samples#423]
Sample gpiokmdf was built successfully. The gear screen displays too. However, VS has info of "Driver Deployment Task Failed: CBS Commit", and there are no other signs representing successful deployment. I am new to driver deployment. Anyone has a similar issue?

**Comment by CaseyLu** [comment]
PS: My win 10 IoT is on Raspberry pi 3

**Comment by IoTGirl** [comment]
Hi CaseyLu,
There is an existing issue at [https://social.msdn.microsoft.com/Forums/Windowsserver/en-US/57d40f2a-399a-46d9-91da-6e6c273baf13/cbs-status-failure-unable-to-debug-the-deploy-driver-to-rpi3?forum=WindowsIoT](https://social.msdn.microsoft.com/Forums/Windowsserver/en-US/57d40f2a-399a-46d9-91da-6e6c273baf13/cbs-status-failure-unable-to-debug-the-deploy-driver-to-rpi3?forum=WindowsIoT ) that indicates this error may have been the result of mis-matched tools.  Can you confirm the actual version number of both the device OS and ADK/SDK/WDK you have installed?
Sincerely,
IoTGirl

**Comment by IoTGirl** [comment]
Hi @CaseyLu,
As you have not responded I would ask that you follow up on the forums thread above if you have more questions regarding this issue.
Sincerely,
IoTGirl
