### ISSUE TITLE
could not find assembly 'platform.winmd'

### ISSUE THREAD

**Issue by ghost** [ms-iot/samples#432]
hello
what went wrong if building of **I2cTestTool** fails with C1107 ?

> could not find assembly 'platform.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable

this occurs with vs2017 and also vs2015('Windows.winmd' instead of 'platform.winmd')
br
Andre

**Comment by IoTGirl** [comment]
Hi Andre,

Have you tried repairing the toolsets in question? ADK/SD?WDK?  Also can you confirm that the versions all match?

Sincerely,
IoTGirl

**Comment by ghost** [comment]
hello
ADK and WDK should not be needed and SDK from both machines is the one included in the VS Editions and both are new installations
br
Andre

**Comment by IoTGirl** [comment]
Hi Andre,
Is this still an open issue for you?
Sincerely,
IoTGirl

**Comment by ghost** [comment]
even if i don't have an answer or solution its now on the big list of not working iot projects
br
Andre
