### ISSUE TITLE
md files

### ISSUE THREAD

**Issue by braegelno5** [ms-iot/samples#44]
Is it possible to have in each project a readme.md with a short project descriptions and dependencies?
:)Torsten

**Comment by reneherrero** [comment]
Now you’re just being picky!  :)

 

Will do…

**Comment by bfjelds** [comment]
Our strategy has been to create in depth descriptions on our documentation site (look under the Samples tab):

http://ms-iot.github.io/content/en-US/win10/StartCoding.htm

Please take a look!

**Comment by braegelno5** [comment]
Thanks i got it. If this link is not in the Main MD file it would be helpfull to place them there also, i think.

**Comment by bfjelds** [comment]
That makes a lot of sense!  We'll look into getting the link into our MD files.

**Comment by djaus2** [comment]
Why not keep that file with the project code in the MS-IOT/Samples<proj> repository? That way updates to the documentation can be part of the specific project updates. Could have an automatic copy mechanism to https://github.com/ms-iot/content/tree/develop/en-US/Docs.

PS I am looking at contributing a new project to Samples. How do I currently get my <proj>.md file up into Docs?

**Comment by zhuridartem** [comment]
Please see https://github.com/ms-iot/content/blob/develop/README.md on how to add new .md files for Docs.You would need to also update _data\_docs-index.json to add a link to new doc.

**Comment by IoTGirl** [comment]
Closing Stale - Site has been overhauled and is scheduled for another soon.
