### ISSUE TITLE
should remove the project.lock.json files.  They are better re-built when the user re-builds their solution

### ISSUE THREAD

**Issue by ericleigh007** [ms-iot/samples#49]
Hello, looks like great stuff here.  Looking forward to more functionality in the OS and samples.

Having the project.lock.json files in the repository is not the correct approach, according to the posts I've read in the Visual Studio forum.

As a minimum workaround, users should be told to remove those files from their local repositories if they clone this one.

-thanks
-e

**Comment by bfjelds** [comment]
Thanks for the feedback!  We'll talk to the Visual Studio team and look into fixing this correctly.

**Comment by bfjelds** [comment]
https://github.com/ms-iot/samples/pull/50

**Comment by ooeygui** [comment]
These were remove in pull 50
