### ISSUE TITLE
Found Error in HID Injection Sample

### ISSUE THREAD

**Issue by aegiMt** [ms-iot/samples#494]
Hello

Please take a look to file HidInject.cpp. Function SetKeyboardUsage and ClearKeyboardUsage does not work correctly pressing more than one key at once...

Fixed version attached (renamed to .txt).

Regards, Andi

[HidInject.txt](https://github.com/ms-iot/samples/files/1084366/HidInject.txt)

**Comment by IoTGirl** [comment]
Hi @aegiMt,
Please submit a code change request rather than sample txt like this.  Code change requests can be code reviewed and accepted in place rather than adding this complexity.
Sincerely,
IoTGirl
