### ISSUE TITLE
DigitalSignageUAP - Does not work on smaller screens

### ISSUE THREAD

**Issue by jpoon** [ms-iot/samples#63]
App not coded for different screen sizes; gets cut off on 7" display.

**Comment by bfjelds** [comment]
Thank you for raising this issue!  We will look into a fix for this.

**Comment by ricl** [comment]
None of the IoT sample apps run well/at all on 800*480 screens (which is a common screen size for the Pi).

**Comment by SlavyMihov** [comment]
This issue has been brought to the attention of the app contributors and will be addressed.

**Comment by IoTGirl** [comment]
Feedback taken by IoT Team member - Closing

**Comment by jpoon** [comment]
@IoTGirl what does that mean? Are the apps being updated to support running on smaller screens?

**Comment by SlavyMihov** [comment]
Yes, the apps have already been updated to display properly on small screens.

**Comment by jpoon** [comment]
Cool. 👍 

gitetiquette: link the issue with the PR.

**Comment by IoTGirl** [comment]
@jpoon I would normally link to the fix, but in this case it looks like the fix has been in for quite some time so we do not have a direct change that we can point to.
