### ISSUE TITLE
Zip files of source code in the sample repo

### ISSUE THREAD

**Issue by jpoon** [ms-iot/samples#64]
https://github.com/ms-iot/samples/blob/develop/AllJoyn/AllJoynZWaveDemo/ZWaveAdapter.zip
https://github.com/ms-iot/samples/blob/develop/AllJoyn/AlljoynMockAdapter/MockAdapter.zip

These are zips of source code. Please expand these zips and put the source codes straight into git?

**Comment by TorstenStein** [comment]
The zip files are provided to contain only the code needed for the sample. You can find the complete open source tree here: https://git.allseenalliance.org/cgit/dsb.git

**Comment by jpoon** [comment]
It's strange to have a zip file of source code within a repository as you prevents browse/search/maintain history of the code through git and GitHub.

As a suggestion, as the dsb.git is a git repo, add these as a git submodule?

**Comment by zhuridartem** [comment]
Hello, and thanks for the feedback. Doing the cross reference as git submodules is a good idea. We did not get around to this yet.

The zip files do come from another git repo that contains more than the samples mentioned. Each zip here is made to be self-contained. We will evaluate the git submodules option.

**Comment by dotMorten** [comment]
This pattern is extremely annoying and prevents us from seeing the history here, bloats the git database and the download. Also the AllJoynExplorer app doesn't even have source code, but just the appx.
If these aren't samples, but copies from elsewhere, what are they doing here in the sample repo?

This isn't how you do versioned source control:
![image](https://cloud.githubusercontent.com/assets/1378165/10471338/cc884520-71c9-11e5-91b7-aab44c969f27.png)

**Comment by ooeygui** [comment]
@zhuridartem is working on a solution for this.

**Comment by zhuridartem** [comment]
Fixed. Thank you for your patience!
