### ISSUE TITLE
Windows Service for IoT ?

### ISSUE THREAD

**Issue by TheUltimateC0der** [ms-iot/samples#65]
Is it possible to write a Service for the RPI 2 ? We want to automatically update our application from our repositorys.

**Comment by bfjelds** [comment]
Servicing is a scenario that we are thinking a lot about currently.  It is definitely on our radar.  I don't have an answer for you right now, but will work at getting an answer for you ASAP.

**Comment by JohnMasen** [comment]
Background App(Aka: headless app) may be an option. it has no UI and can start automatically with OS.
ps: you need use IoTStartup command to set your headless app run at startup.

**Comment by mms-** [comment]
Common scenarios for a Windows Service or a Background App are 'is the app running and healthy if not restart' and 'update the app'. Both of these should be handled by the platform. 

That is Windows IoT could (does?) have an update mechanism, something like ClickOnce (but reliable) or APPX or whatever. It should also have a durability feature, so an ability to set an app as foreground app, meaning it is always running and visible (in the case of a headed app) and is actively being checked for to enforce this, not just on start-up. It should also have a basic health query API, if the app does not respond it is shutdown and restarted.

**Comment by bfjelds** [comment]
Thank you for the feedback!  

When an app is specified as a startup app (it has been configured to be a foreground app that is always running and visible), the platform is ensuring that this app is always running.  You can see how to configure the Startup App in the 'Set HelloWorld as the Startup App' section of [here](http://ms-iot.github.io/content/en-US/win10/samples/HelloWorld.htm).

We are working to bring more system management APIs into our platform and appreciate the suggestions for health query, servicing (update), etc.

**Comment by mms-** [comment]
Good to know that always running check is already in there. I haven't had time to play around with the start-up functionality yet.

One un-related issue that we ran in to is the high CPU usage on Raspberry Pi with webcams : https://github.com/ms-iot/samples/issues/30

**Comment by bfjelds** [comment]
Regarding the CPU usage, we are still working on implementing the graphics driver for the Raspberry Pi. This results in many GPU operations being handled by software. You are seeing the results of that first hand. Be assured that we are well aware of this and working to fix it!

**Comment by TheUltimateC0der** [comment]
Hey guys,

thank you for your fast reply.

@JohnMasen : Background Apps, are not suitable for my needs, i have to access the filesystem, in order to update my application. As far as i know, you cannot access the filesystem as from a normal UWP application. If i missed something, please point me to the right direction :)

@mms- : Good mention with the ClickOnce. That would be very handy to use. Another possible way would be, to publish the application to the normal store, so others can install them on their devices as well, from like Webb ?! maybe ?. I think it is just easy as a pie, for the @msftgits guys to add a new category or something like that. I think that would be a plus for the new eco system, microsoft is trying to implement with iot.

Cheers Guys !

**Comment by TheUltimateC0der** [comment]
Hey guys. Any updates here ?

**Comment by bfjelds** [comment]
We created a simple C++ service based on the C++ Console Application template that can be used to create a service for IoT Core:

https://github.com/ms-iot/samples/pull/119

Hope this helps!!

**Comment by mms-** [comment]
Will try the C++ service soon. What is the recommended way to run C# code within that? Or can the service also be C# based without loss of functionality?

**Comment by bfjelds** [comment]
Only C++ is supported for console applications and services currently.

**Comment by TheUltimateC0der** [comment]
When will VB.Net or C# will be supported ?

**Comment by mms-** [comment]
Is it managed C++ that can call managed c# assemblies?

**Comment by bfjelds** [comment]
Outside of WinRT, we don't have plans to support managed code on IoT Core.

For the service sample, it is not managed C++.

**Comment by mms-** [comment]
That makes sense, I assume then that WinRT will grow in capability and WinRT based services or equivalent will arrive at some point. Hopefully not years..
