### ISSUE TITLE
Memory leak in IoTCoreDefaultApp

### ISSUE THREAD

**Issue by ricl** [ms-iot/samples#73]
![iotcoredeafaultapp](https://cloud.githubusercontent.com/assets/7289122/10050152/d3cbb9be-6212-11e5-8f04-c602bce05e66.png)

![iotcoredeafaultapp2](https://cloud.githubusercontent.com/assets/7289122/10050572/ec7a0ea0-6214-11e5-96bf-c3524f2231ad.png)

![iotcoredeafaultapp3](https://cloud.githubusercontent.com/assets/7289122/10050718/9e3d8afe-6215-11e5-8752-76a576be8aae.png)

Running IoTCoreDefaultApp on both the Pi and the Desktop creates a memory leak when navigating to/from the Tutorials page.

Reproduction:

Run IoTCoreDefaultApp and observe the memory used (via Visual Studio on the Desktop, http://192.168.1.19:8080/SystemPerformance.htm on the Pi).

Navigating between Tutorials and Device Info (and around inside Tutorials) causes memory to be allocated and never released. This is even true after GC.

**Comment by bfjelds** [comment]
Thank you for finding this and bringing it to our attention!  We'll work on fixing this ASAP.

**Comment by ricl** [comment]
It would appear that both

```
        Frame rootFrame = Window.Current.Content as Frame;
        rootFrame.Navigate(screenType, parameter);
```

and

```
        Frame rootFrame = Window.Current.Content as Frame;
        rootFrame.GoBack();
```

ALWAYS call the constructor on the Page referenced. This is regardless as to whether the Page is in the BackStack or not.

**Comment by ricl** [comment]
SOLVED:

Add

...
            this.InitializeComponent();
            this.NavigationCacheMode = NavigationCacheMode.Enabled;
...

to all the pages to allow for correct BackStack implementation on IoT Core.

Constriuctors are then not called (unless needed) on .Navigate(...) or .GoBack()

**Comment by bfjelds** [comment]
Thank you for sorting this out!  We will work to update our samples accordingly.

**Comment by bfjelds** [comment]
This has been addressed with https://github.com/ms-iot/samples/pull/98
