### ISSUE TITLE
IoTCoreDefaultApp Language Setting does not change input locale

### ISSUE THREAD

**Issue by PatGet** [ms-iot/samples#78]
IoTCoreDefaultApp Language Setting does not change input locale. For example the second part of the OOB Expirience is WIFI Network Password. All the UI there is presented in German language to me but I have to type in the Password as if i had an english Keyboard.

**Comment by grahamehorner** [comment]
@PatGet have you performed a reboot after changing the Language Settings; I had something similar with regards to date/time region; and it's because of the system/thread culture change isn't detected by the app.

A restart stored it for me

**Comment by grahamehorner** [comment]
https://github.com/ms-iot/samples/issues/147

**Comment by bfjelds** [comment]
This locale change issue is a problem with the OS currently that we are working to fix.

**Comment by rachitb777** [comment]
We have added Keyboard layout setting in the IoTCoreDefaultApp. Skip OOBE and then goto settings to change the keyboard layout.
